"""Tests for the DocILE PDF -> PNG rasterizer.

The fixture PDF at ``tests/fixtures/docile/pdfs/aaa…003.pdf`` is a
1-page blank US-Letter document generated by
``synthetic_data.docile._make_pdf_fixture`` (committed to the repo
since DocILE's real PDFs are CC BY-NC-ND-licensed and not
redistributed here). Multi-page coverage uses a tmp_path-generated
PDF so we don't have to commit multiple binaries.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

from synthetic_data.docile._make_pdf_fixture import make_blank_pdf
from synthetic_data.docile.rasterize import (
    PDF_POINTS_PER_INCH,
    RASTERIZE_DPI,
    RasterizedPage,
    rasterize_document,
)

FIXTURE_PDF_DIR = Path(__file__).parent / "tests" / "fixtures" / "docile" / "pdfs"
FIXTURE_DOC_ID = "aaa000000000000000000003"
FIXTURE_PDF = FIXTURE_PDF_DIR / f"{FIXTURE_DOC_ID}.pdf"


def test_rasterize_dpi_default_is_200() -> None:
    """Default DPI matches DocILE's `page_sizes_at_200dpi` upstream convention."""
    assert RASTERIZE_DPI == 200


def test_rasterize_single_page_fixture(tmp_path: Path) -> None:
    """Smoke test against the committed 1-page blank fixture."""
    results = rasterize_document(FIXTURE_PDF, tmp_path, FIXTURE_DOC_ID)
    assert len(results) == 1
    page = results[0]
    assert isinstance(page, RasterizedPage)
    assert page.page_number == 1
    assert page.png_path == tmp_path / f"{FIXTURE_DOC_ID}-p1.png"
    assert page.png_path.is_file()
    # US Letter (612pt x 792pt) at 200 DPI = 1700 x 2200.
    assert page.width_px == 1700
    assert page.height_px == 2200
    # Sanity-check the PNG actually decodes to those dimensions.
    with Image.open(page.png_path) as img:
        assert img.size == (1700, 2200)


def test_rasterize_multi_page_pdf(tmp_path: Path) -> None:
    """Three-page blank PDF rasterizes to three PNGs with 1-indexed names."""
    pdf_path = tmp_path / "multi.pdf"
    make_blank_pdf(pdf_path, num_pages=3)

    out_dir = tmp_path / "rendered"
    results = rasterize_document(pdf_path, out_dir, "MULTI-DOC")
    assert [r.page_number for r in results] == [1, 2, 3]
    assert [r.png_path.name for r in results] == [
        "MULTI-DOC-p1.png",
        "MULTI-DOC-p2.png",
        "MULTI-DOC-p3.png",
    ]
    for r in results:
        assert r.png_path.is_file()
        assert r.width_px == 1700
        assert r.height_px == 2200


def test_rasterize_custom_dpi_scales_dimensions(tmp_path: Path) -> None:
    """Halving the DPI halves the pixel dimensions."""
    pdf_path = tmp_path / "blank.pdf"
    make_blank_pdf(pdf_path, num_pages=1)

    results = rasterize_document(pdf_path, tmp_path, "DOC", dpi=100)
    assert len(results) == 1
    # 612pt x 792pt at 100 DPI = 850 x 1100.
    assert results[0].width_px == 850
    assert results[0].height_px == 1100


def test_rasterize_creates_output_directory(tmp_path: Path) -> None:
    """Non-existent out_dir is created."""
    pdf_path = tmp_path / "blank.pdf"
    make_blank_pdf(pdf_path, num_pages=1)
    out_dir = tmp_path / "deep" / "nested" / "render"
    assert not out_dir.exists()

    rasterize_document(pdf_path, out_dir, "DOC")
    assert out_dir.is_dir()


def test_rasterize_overwrites_existing_png(tmp_path: Path) -> None:
    """Re-rasterizing into the same dir overwrites in place (idempotent output)."""
    pdf_path = tmp_path / "blank.pdf"
    make_blank_pdf(pdf_path, num_pages=1)

    first = rasterize_document(pdf_path, tmp_path, "DOC")
    assert first[0].png_path.is_file()
    first_mtime = first[0].png_path.stat().st_mtime_ns

    second = rasterize_document(pdf_path, tmp_path, "DOC")
    assert second[0].png_path == first[0].png_path
    # File was re-written; mtime should be >= original (== on very fast disks).
    assert second[0].png_path.stat().st_mtime_ns >= first_mtime


def test_points_per_inch_constant() -> None:
    """PDF spec constant — guards against accidental edits."""
    assert PDF_POINTS_PER_INCH == 72


def test_make_blank_pdf_rejects_zero_pages(tmp_path: Path) -> None:
    """A zero-page PDF would silently break rasterizer contracts."""
    import pytest

    with pytest.raises(ValueError, match="positive int"):
        make_blank_pdf(tmp_path / "bad.pdf", num_pages=0)


def test_make_blank_pdf_rejects_negative_pages(tmp_path: Path) -> None:
    """Negative page counts are obvious input typos — fail fast."""
    import pytest

    with pytest.raises(ValueError, match="positive int"):
        make_blank_pdf(tmp_path / "bad.pdf", num_pages=-3)
