"""One-shot generator for the DocILE rasterizer's test PDF fixture.

DocILE's real PDFs are CC BY-NC-ND-licensed and not redistributed in
this MIT repo; the rasterizer's unit tests run against a blank PDF
generated by this helper. The fixture is reproducible byte-for-byte
across pypdfium2 versions of the same major (5.x) — re-run after a
pypdfium2 major bump to regenerate.

Usage::

    uv run python -m synthetic_data.docile._make_pdf_fixture \\
        tests/fixtures/docile/pdfs/aaa000000000000000000003.pdf

The committed fixture matches the minimal-document annotation fixture
(``aaa000000000000000000003``) so end-to-end rasterize+parse tests can
correlate by doc_id.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pypdfium2 as pdfium

LETTER_WIDTH_PT = 612
"""US Letter width in PDF points (1/72 inch). 8.5 inches *72."""
LETTER_HEIGHT_PT = 792
"""US Letter height in PDF points (1/72 inch). 11 inches *72."""


def make_blank_pdf(out_path: Path, *, num_pages: int = 1) -> Path:
    """Write a US-Letter-sized ``num_pages``-page blank PDF at ``out_path``."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc = pdfium.PdfDocument.new()
    try:
        for _ in range(num_pages):
            doc.new_page(LETTER_WIDTH_PT, LETTER_HEIGHT_PT)
        with out_path.open("wb") as fh:
            doc.save(fh)
    finally:
        doc.close()
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a blank PDF fixture for the rasterizer tests."
    )
    parser.add_argument(
        "out_path",
        type=Path,
        help="Output PDF path (e.g., tests/fixtures/docile/pdfs/<doc_id>.pdf).",
    )
    parser.add_argument(
        "--pages",
        type=int,
        default=1,
        help="Number of blank pages. Default: 1.",
    )
    args = parser.parse_args()
    written = make_blank_pdf(args.out_path, num_pages=args.pages)
    print(f"Wrote {written} ({args.pages} page(s)).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
